name: Build & Deploy React to EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_USER: ec2-user
      DEPLOY_PATH: /var/www/react-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js (npmjs registry)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      # --- Auth for private npmjs packages ---
      # This ~/.npmrc makes npm ALWAYS send the token to registry.npmjs.org
      # (helps when a dependency internally does an authenticated fetch).
      - name: Configure npm auth
        run: |
          echo "always-auth=true" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" >> ~/.npmrc

      - name: Show active registry (sanity check)
        run: npm config get registry

      - name: Install deps (private npmjs.com)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm ci

      - name: Build
        env:
          CI: "false"
        run: npm run build:test

      - name: Configure SSH
        run: |
          install -m 600 /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.DEPLOY_HOST }}" >> ~/.ssh/known_hosts

      - name: Create release dir on server
        run: |
          TS=$(date +%Y%m%d%H%M%S)
          echo "RELEASE=$TS" >> $GITHUB_ENV
          ssh -i ~/.ssh/id_rsa $EC2_USER@${{ secrets.DEPLOY_HOST }} "mkdir -p $DEPLOY_PATH/releases/$TS"

      - name: Rsync build to server
        run: |
          rsync -az --delete -e "ssh -i ~/.ssh/id_rsa" \
            build/ $EC2_USER@${{ secrets.DEPLOY_HOST }}:$DEPLOY_PATH/releases/${{ env.RELEASE }}/

      - name: Activate release (symlink + nginx reload)
        run: |
          ssh -i ~/.ssh/id_rsa $EC2_USER@${{ secrets.DEPLOY_HOST }} "\
            ln -sfn $DEPLOY_PATH/releases/${{ env.RELEASE }} $DEPLOY_PATH/current && \
            if command -v nginx >/dev/null 2>&1; then \
              sudo nginx -t && sudo systemctl reload nginx || sudo systemctl restart nginx; \
            fi \
          "

      - name: Cleanup old releases (keep last 5)
        run: |
          ssh -i ~/.ssh/id_rsa $EC2_USER@${{ secrets.DEPLOY_HOST }} "\
            ls -1dt $DEPLOY_PATH/releases/* | tail -n +6 | xargs -r rm -rf \
          "
